name: Publish to github packages and create a draft release

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Fix permissions
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew gdx-LEdMap:build

      - name: Publish package
        run: ./gradlew gdx-LEdMap:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch version
        run: ./gradlew gdx-LEdMap:currentVersion

      - name: Set version in script
        run: echo "VERSION=$(cat gdx-LEdMap/build/version.txt)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: gdx-LEdMap ver. ${{ env.VERSION }}
          draft: true
          prerelease: false

      - name: Upload jar release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: gdx-LEdMap/build/libs/gdx-LEdMap-${{ env.VERSION }}.jar
          asset_name: gdx-LEdMap-${{ env.VERSION }}.jar
          asset_content_type: application/x-java-archive
