name: Build, Test, Publish

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Fix permissions
        run: chmod +x gradlew

      - name: Test project
        run: ./gradlew gdx-LEdMap:check

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.2
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: gdx-LEdMap/build/test-results/**/*.xml
          report_individual_runs: true


  Publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Fix permissions
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew gdx-LEdMap:build

      - name: Fetch version
        run: ./gradlew gdx-LEdMap:currentVersion

      - name: Set version in script
        run: echo "VERSION=$(cat gdx-LEdMap/build/version.txt)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: (CI) gdx-LEdMap ${{ env.VERSION }}
          draft: false
          prerelease: true

      - name: Upload jar release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: gdx-LEdMap/build/libs/gdx-LEdMap-${{ env.VERSION }}.jar
          asset_name: gdx-LEdMap-${{ env.VERSION }}.jar
          asset_content_type: application/x-java-archive
