name: Build, Test, Publish

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Fix permissions
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew gdx-LEdMap:check

  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Fix permissions
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew gdx-LEdMap:build

      - name: Publish package
        run: ./gradlew gdx-LEdMap:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
