name: Publish to github packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Fix permissions
        run: chmod +x gradlew

      - name: Publish package
        run: ./gradlew gdx-LEdMap:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}